sudo: false

language: node_js

node_js:
  - 0.10

addons:
  apt:
    sources:
      - mongodb-upstart
    packages:
      - mongodb-org-server

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - "gem install sass"
  - npm install -g npm@latest

before_script:
  - export DISPLAY=:99.0
  - export COCO_TRAVIS_TEST=1
  - sh -e /etc/init.d/xvfb start
  - "node index.js --unittest &"
  - "sleep 10" # to give node a chance to start

script:
  - "./node_modules/jasmine-node/bin/jasmine-node test/server/ --coffee --captureExceptions"
  - "./node_modules/karma/bin/karma start --browsers Firefox --single-run --reporters progress"
